### ISSUE TITLE
Introductory example doesn't work - `view(robj, window)` has no method

### ISSUE THREAD

**Issue by cormullion** [JuliaGL/GLVisualize.jl#124]
Trying to run [the introduction](http://www.glvisualize.com/examples/introduction/), I get as far as:

```
julia> view(robj, window)
ERROR: MethodError: no method matching 
    view(::GLAbstraction.Context{GLAbstraction.DeviceUnit}, ::GLWindow.Screen)

```
`robj` and `window` seem to be OK though:

```
julia> window
name: GLVisualize
children: 0
Inputs:
  framebuffer_size => Reactive.Signal{FixedSizeArrays.Vec{2,Int64}}
....
julia> typeof(robj)
GLAbstraction.Context{GLAbstraction.DeviceUnit}

julia> typeof(window)
GLWindow.Screen
```

Everything has just been downloaded from github:

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

**Comment by SimonDanisch** [comment]
Sorry, haven't updated the website yet. 
Also, I'm just about to tag a new version. It'd be simplest if you just check out the newest version, until my PR gets merged in METADATA.
`Pkg.checkout("GLVisualize"); Pkg.checkout("GLAbstraction"); Pkg.checkout("GLWindow");`
Then run all the examples with:
`Pkg.test("GLVisualize")` or checkout `https://github.com/JuliaGL/GLVisualize.jl/tree/master/examples`
You will see that `view` was renamed to `_view` due to clashes with Base.

Best,
Simon

**Comment by musm** [comment]
Sucks that we can't use `view`  having the underscore in `_view` kinda bothers me. Makes it look private even though it's a central function. Perhaps some name  like `viz`  might be better?

**Comment by cormullion** [comment]
@SimonDanisch Cool. I should've guessed it was the old name clash thing...

**Comment by SimonDanisch** [comment]
Yeahh, so, I have been slow on this, because it kinda _is_ a private function... I mean, in something like GLPlot, the user shouldn't really worry about this, you should just be able to say `plot x in window y`
