### ISSUE TITLE
UndefVarError: Mat not defined

### ISSUE THREAD

**Issue by pauljurczak** [JuliaGL/GLVisualize.jl#185]
I'm using Julia 0.6 on Windows 7 64-bit. `Pkg.add("GLVisualize")` went fine, but `Pkg.test("GLVisualize")` produces number of errors starting with:

WARNING: both GeometryTypes and FixedSizeArrays export "Mat"; uses of it in module GLAbstraction must be qualified
ERROR: LoadError: LoadError: UndefVarError: Mat not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:569
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:569
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\Paul\.julia\v0.6\GLAbstraction\src\composition.jl, in expression starting on line 76
while loading C:\Users\Paul\.julia\v0.6\GLAbstraction\src\GLAbstraction.jl, in expression starting on line 57

BTW, I reproduced the same problem on Ubuntu 16.04.

**Comment by phileas2** [comment]
The problem resides in the file `C:\Users\Paul.julia\v0.6\GLAbstraction\src\composition.jl`. 
You have to edit it by importing `FixedSizeArrays` elements :  `Mat`, `Vec`, and `Point`.

Make sure you add the following line :

 `import FixedSizeArrays: Mat, Vec, Point`

at the beginning of all these files :

`C:\Users\Paul.julia\v0.6\GLAbstraction\src\composition.jl`
`C:\Users\Paul.julia\v0.6\GLAbstraction\src\GLCamera.jl`
`C:\Users\Paul.julia\v0.6\GLWindow\src\types.jl`
 
in order to avoid more similar errors.

**Comment by SimonDanisch** [comment]
GLVisualize wasn't 0.6 compatible. This is solved in the newest release:
https://github.com/JuliaLang/METADATA.jl/pull/10247
