### ISSUE TITLE
Visualizing color volumes

### ISSUE THREAD

**Issue by timholy** [JuliaGL/GLVisualize.jl#198]
I am interested in interactive visualization of 3d `RGBA{N0f8}` volumes, where I've already set the alpha channel the way I want an absorbance model to work. (Even better: pass an `Array{Int32,3}` of voxel labels, plus some kind of `Vector{RGBA{N0f8}}` lookup table. But one step at a time :wink:.) I'm hoping to do this on a short timetable, so I plan on implementing it myself but could use some pointers here and there.

If I understand correctly, the things I'd need to do to enable this are:
- write vertex and fragment shaders. I plan on calling them `colorvolume.vert` and `colorvolume.frag`.
- add an apprpriate `_default` method to [image_like.jl](https://github.com/JuliaGL/GLVisualize.jl/blob/master/src/visualize/image_like.jl).

Anything else? Know of any shaders I can start from?

**Comment by SimonDanisch** [comment]
I wonder if we should turn this into making a point about why Transpiler.jl is great for this... Since if the current volume shader would already be written in Julia, the element type should just work naturally with the current implementation.
I already ported the volume shader to work with transpiler: [volume.jl](https://github.com/SimonDanisch/Visualize.jl/blob/master/src/shader/volume.jl)
We could also think about slowly sneaking in Transpiler.jl into GLVisualize like this. Only Problem: I still need to recover the OpenGL transpilation, which is 80% done.
Would you be up for that?  I could set you up  with a version that runs on the CPU already, which you can use to implement the algorithm.

Otherwise you seem to be on the right track! Maybe don't create `colorvolume.vert` and `colorvolume.frag` and rather integrate it in the current `uber` (volume shader)[https://github.com/JuliaGL/GLVisualize.jl/blob/master/assets/shader/volume.frag].

Should be only a few changes to that file to make things work with `RGBA{N0f8}`.

**Comment by timholy** [comment]
That sounds really attractive. I'm not sure I fully understand your vision, but the more julia and less shader language, the better :smile:. Is there a part I should start on in the meantime? Perhaps the `_default` method?

**Comment by timholy** [comment]
Oh, wait, I think I see. You're saying the short term we should modify the shader. Working on it.

**Comment by SimonDanisch** [comment]
Yes, that's probably the easiest for now!

**Comment by timholy** [comment]
x-ref #199

**Comment by SimonDanisch** [comment]
I think you solved this :)
