### ISSUE TITLE
GLVisualize fails on precompilation

### ISSUE THREAD

**Issue by mmoh** [JuliaGL/GLVisualize.jl#24]
I can't get this to work. I copy and pasted the install script. (Windows  10)
```
INFO: Precompiling module GLVisualize...
ERROR: LoadError: __precompile__(false) is not allowed in files that are being precompiled
 in __precompile__ at loading.jl:162
while loading C:\Users\mmoh\.julia\v0.5\Images\src\Images.jl, in expression starting on line 1
ERROR: LoadError: Failed to precompile Images to C:\Users\mmoh\.julia\lib\v0.5\Images.ji
 in error at error.jl:21
while loading C:\Users\mmoh\.julia\v0.5\GLAbstraction\src\GLAbstraction.jl, in expression starting on line 10
ERROR: LoadError: Failed to precompile GLAbstraction to C:\Users\Mustafa\.julia\lib\v0.5\GLAbstraction.ji
 in error at error.jl:21
while loading C:\Users\mmoh\.julia\v0.5\GLWindow\src\GLWindow.jl, in expression starting on line 4
ERROR: LoadError: Failed to precompile GLWindow to C:\Users\mmoh\.julia\lib\v0.5\GLWindow.ji
 in error at error.jl:21
while loading C:\Users\mmoh\.julia\v0.5\GLVisualize\src\GLVisualize.jl, in expression starting on line 5
ERROR: Failed to precompile GLVisualize to C:\Users\mmoh\.julia\lib\v0.5\GLVisualize.ji
 in error at error.jl:21
```

```
Julia Version 0.5.0-dev+9
Commit 248eb0b (2015-09-10 04:03 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by SimonDanisch** [comment]
Are you sure `Pkg.checkout("Images", "sd/fileio")` was successfull?

**Comment by mmoh** [comment]
So I redid the installation procedure. Now this is the error I'm getting with testing the package

```
julia> Pkg.test("GLVisualize")
INFO: Testing GLVisualize
INFO: Recompiling stale cache file C:\Users\Mustafa\.julia\lib\v0.5\MeshIO.ji for module MeshIO.
Barplot
3d dot particles
ERROR: LoadError: LoadError: MethodError: `*` has no method matching *(::FixedSizeArrays.Mat{4,4,Float32}, ::GeometryTypes.HyperRectangle{3,Float32})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
  *{T,M,N,K}(::FixedSizeArrays.Mat{M,N,T}, ::FixedSizeArrays.Mat{N,K,T})
  *{T,M,N,O,K}(::FixedSizeArrays.FixedArray{T,2,Tuple{M,N}}, ::FixedSizeArrays.FixedArray{T,2,Tuple{O,K}})
  ...
 in consume at C:\Users\Mustafa\.julia\v0.5\GLAbstraction\src\GLUtils.jl:109
 in lift at C:\Users\Mustafa\.julia\v0.5\Reactive\src\Reactive.jl:362
 in default_boundingbox at C:\Users\Mustafa\.julia\v0.5\GLVisualize\src\utils.jl:61
 in visualize at C:\Users\Mustafa\.julia\v0.5\GLVisualize\src\utils.jl:18
 in dots_data at C:\Users\Mustafa\.julia\v0.5\GLVisualize\test\all_tests.jl:23
 in include at boot.jl:260
 in include_from_node1 at loading.jl:271
 in include at boot.jl:260
 in include_from_node1 at loading.jl:271
 in process_options at client.jl:308
 in _start at client.jl:411
while loading C:\Users\Mustafa\.julia\v0.5\GLVisualize\test\all_tests.jl, in expression starting on line 25
while loading C:\Users\Mustafa\.julia\v0.5\GLVisualize\test\runtests.jl, in expression starting on line 12
============================================[ ERROR: GLVisualize ]=============================================

failed process: Process(`'C:\Julia\Julia-0.5.0-dev\bin\julia' --check-bounds=yes --code-coverage=none --color=yes 'C:\Users\Mustafa\.julia\v0.5\GLVisualize\test\runtests.jl'`, ProcessExited(1)) [1]

===============================================================================================================
ERROR: GLVisualize had test errors
 in error at error.jl:21
```

**Comment by SimonDanisch** [comment]
My bad! Forgot to push some commits.
Can you checkout `GLVisualize` and `GeometryTypes`?!

**Comment by mmoh** [comment]
Hmm I did a checkout on both packages but it said nothing to update or change?
same error.

**Comment by SimonDanisch** [comment]
Maybe a problem with `Pkg`? Have you tried to manually pull the newest master?

**Comment by mmoh** [comment]
So I deleted everything in  .julia and reinstalled according to the install instructions, getting the same error...

**Comment by SimonDanisch** [comment]
I just made sure: on Github master, the changes have arrived...
So has this script:
```Julia
Pkg.clone("https://github.com/JuliaIO/FileIO.jl.git")
Pkg.clone("https://github.com/JuliaIO/MeshIO.jl.git")
Pkg.clone("https://github.com/JuliaGeometry/Packing.jl.git")
Pkg.clone("https://github.com/JuliaIO/ImageMagick.jl.git")
Pkg.build("ImageMagick")
Pkg.clone("https://github.com/JuliaGL/GLVisualize.jl.git")
Pkg.checkout("Images", "sd/fileio")
Pkg.checkout("GeometryTypes")
Pkg.checkout("FixedSizeArrays")
Pkg.checkout("Meshes", "ntuples")
Pkg.checkout("ModernGL")
Pkg.checkout("GLWindow")
Pkg.checkout("GLAbstraction")
```
really run without errors?
What does `Pkg.status()` say?
It should say something like:
```
 - GeometryTypes                 0.0.2+             master
 - GLVisualize                   0.0.0-             master (unregistered)
```

**Comment by mmoh** [comment]
Great, not sure what you did, but now all tests pass, sans some depreciated warnings!

**Comment by mmoh** [comment]
Looking forward to  documentation :wink:

**Comment by SimonDanisch** [comment]
ahaha, yeah... non existent ;) Until I wrote them, don't hesitate to ask any question please!

**Comment by hustf** [comment]
Hello, I have much of the same problem as mmoh. Actually, I have been trying to make GLPlot work for a while now. As of yet, I am quite new to the whole github / open source that I fear I may create a mess. Still, I hope I can contribute in a small way. The problems are probably caused by various dependencies, but perhaps this is a good place to report, and to find a working set of packages? 

I have a 32-bit notepad with Windows 10, and a 64 bit Mac with graphics card GeForce GTX 775M. The mac has an OS X Yosemite parition and a Windows 8.1 partition (which I plan to upgrade soon). None of them are working with the versions of Julia I tried so far. I started out using Juno, but for making this work I believe the console is more efficient.

How can I report efficiently? What would you be most interested in? Should I ignore warnings regarding deprecated syntax in required packages? I also don´t know when to use github and when to use the Julia package manager. Would the Julia package manager be confused if I fork / branch and so forth from Github?

**Comment by SimonDanisch** [comment]
@hustf just open an issue at GLVisualize ;) Most interesting is the error message, OS and OpenGL version. You only need to get the OpenGL version when I ask, since it's usually not the problem ;)
Warnings are mostly fine, although I try to keep everything free from warnings (there are some I can't easily get rid of while building, though).

The package manager should be mostly fine with forks and branches... I'm on windows where the package manager is really slow, so I only add packages with it and do the rest via git/github desktop.

Best,
Simon

**Comment by hustf** [comment]
Thanks for that; I have run some tests already,  and will open a separate issue in a few minutes. The OpenGL Version will be 4.1, and OpenCL 1.2 on the Mac/Windows computer
.
