### ISSUE TITLE
GLVisualize no longer works for simple plot

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGL/GLVisualize.jl#65]
The following didn't render anything:

```julia
using GLVisualize
w=glscreen();
x=y=Float32[1:10;];
z=Float32[exp(x+2y) for x in x, y in y];

vis=visualize((x*ones(y)', ones(x)*y', z), :surface);

 view(vis,w)

renderloop(w)
```

**Comment by SimonDanisch** [comment]
duplicate of #50 ?

**Comment by dlfivefifty** [comment]
No I don't think so: this time it doesn't error out

**Comment by SimonDanisch** [comment]
but the z goes from `20 - 1.0686474e13`

**Comment by dlfivefifty** [comment]
Oh..duh

**Comment by SimonDanisch** [comment]
by the way there is now: `center!(::window, [camera=:perspective])`, which centers the camera to all objects in the window. It's only on master of `GLAbstraction` right now, but I'll tag a new version soon!
Note, that it wouldn't have done anything in your situation, since the object was way too thin.
