### ISSUE TITLE
Rules for rotation between OpenGL and GLVisualize and V-REP

### ISSUE THREAD

**Issue by kleinash** [JuliaGL/GLVisualize.jl#89]
Hi,

I am not coming out with the same picture that I should be when I generate a depth image. Let me set the scene:

I have a scene in V-REP: 

![scene_img_before_grasp_22](https://cloud.githubusercontent.com/assets/2494123/14629876/fc2b9140-0609-11e6-9e3a-a25cb2aa16b2.jpg)

I want a depth image from the perspective of the hand. The orientation of the camera is the same of that of the hand and the distance is ~0.3m behind the hand, this is a snippet: 

```julia
rot_mx = rotEuler(gripper_orient[grasp_num][1], gripper_orient[grasp_num][2], gripper_orient[grasp_num][3])
lookatdirection = FixedSizeArrays.Vec{3,Float32}(rot_mx * [0; 0; 1])
eyeposition = gripper_position[grasp_num] - (cam_dis * lookatdirection)
camera_up = rot_mx * [0;1;0]
          
push!(cam.lookat, gripper_position[grasp_num])
push!(cam.eyeposition, eyeposition)
push!(cam.up, camera_up)
push!(cam.farclip, 10f0)
push!(cam.nearclip, 0.1f0)
push!(cam.fov, 70f0) 
```

The orientation of the gripper is in Euler values apha, beta, gamma and the rot_mx is rx * ry * rz. 

It all seems right, but I think there is something thats different between the V-REP rotations to OpenGL rotations to GLVisualize ... 

This is what I am getting out:

![25_mug-02-feb-2016-12-40-43 obj131022](https://cloud.githubusercontent.com/assets/2494123/14638636/78e335a2-0638-11e6-8e38-6ae42764d8e6.png)

Thx

**Comment by SimonDanisch** [comment]
`GLVisualize/examples/camera/camera.jl` works fine on my machine, indicating that the camera works fine if you set `up`, `eyeposition` and `lookat` correctly. So I'm guessing you simply calculated them wrong? Did you try visualizing them, like in the camera example? Make sure that  `up`, `eyeposition` and `lookat` are orthogonal to each other!

**Comment by kleinash** [comment]
Just to make sure 
up is the top of the camera vector
eyeposition is an xyz position of the camera and 
lookat is a point to look at thats in front of the camera (not necessarily on the object you are looking at)

**Comment by SimonDanisch** [comment]
Sounds right...This should make it very clear:
http://www.glvisualize.com/examples/camera/#camera
The spheres are lookat and eyeposition, green is up. Blue is right and red is the direction (which aren't part of the camera, since they get calculated on the fly).

**Comment by kleinash** [comment]
Ok working through that now - last question here - my first image does not generate. I have this scene: 
![scene_img_before_grasp_1](https://cloud.githubusercontent.com/assets/2494123/14640377/91e9af1e-0641-11e6-8c0c-4781c178e36f.jpg)

but I get out a blank:

![25_mug-02-feb-2016-12-40-43 obj131001](https://cloud.githubusercontent.com/assets/2494123/14640388/9bdc051c-0641-11e6-86e0-fb226fa69686.png)

**Comment by SimonDanisch** [comment]
Please, can you just get into the habit of creating minimal examples that I can just execute to see if I can reproduce your problem? Creating these minimal examples should also help you to figure out what the actual problem is. If you can create a minimal example with e.g. only a cube and one camera, without any external grabber library, where the camera is obviously not working correctly, that would be brilliant.
```
I want this:
[image]
but got this:
[image]
```
How do you expect me to give you any meaningful advice here?
Please consider that I have a very restricted time budget and really only want to spent my time on actual `GLVisualize` bugs and documentation issues. In the way you post your issues, it cost me already a lot of time to figure out if GLVisualize is at fault, or if you just didn't setup things correctly.

Besides that, I do appreciate your bravery of working on GLVisualize master and being the first to actually report bugs that happen.

You might want to check, if V-REP has a different up vector it assumes for the 3D objects you load.

**Comment by kleinash** [comment]
My example has not changed from the beginning. This minimal example is the same as the first comment in this issue, and it comes from the same depth image generation question. I probably should have put links to all my other issues listed. I have been trying to to ensure my orientations are correct and aside from that I have to leave out the first image of my set because it doesn't spawn. This may be linked to the orientations, or it may be something internal. Either way I didn't think it was something the forum would be interested in. 

Again I appreciate your time. I can close this and move to the forum.

**Comment by SimonDanisch** [comment]
Your first example is not a minimal example, that I can simply execute and reproduce...

**Comment by kleinash** [comment]
Ok cool - sorry about that. I may just be brain storming here. Will def update my style of questioning.

**Comment by vchuravy** [comment]
@kleinash Your questions are definitely welcome, but keep in mind that we are all doing this as volunteers and because we are excited about Julia. So if you have a question/problem best make the life of the people you are asking as easy as possible.

Otherwise welcome to the Julia community and I am excited to see what you are going to come up (looks like deep-learning for robotics?)

**Comment by kleinash** [comment]
@vchuravy Will try keep questions to the users group and things I think are bugs in issues. Also will have to update my method of questioning, I know how frustrating it is not being able to make heads or tails of a question. 

Yup - robotics, deep learning and mainly neuroscience - at least thats the idea. Julia is definitely my preferred language.
