### ISSUE TITLE
How to correctly import a mesh and generate a depth image. 

### ISSUE THREAD

**Issue by kleinash** [JuliaGL/GLVisualize.jl#96]
Hi,

Yes, I am still struggling with this. 

Attached is a txt file with my object (.obj). This is a simple generation: 

```julia 

using GLVisualize, GLAbstraction, Reactive, GLWindow, PyPlot, GeometryTypes, FileIO

mesh = "1_Coffeecup_final-03-Mar-2016-18-50-40.obj" # attached, just remove the .txt
w = glscreen(resolution=(128, 128))
robj     = visualize(GLNormalMesh(loadasset(mesh)))
GLVisualize.view(robj) 

lookatvec = [0; 0; -1]
eyeposition = [0; 0; 1]

cam = w.cameras[:perspective]
push!(cam.lookat, lookatvec)
push!(cam.eyeposition, eyeposition)
push!(cam.up, Vec3f0(0,0,1))
push!(cam.farclip, 10f0)
push!(cam.nearclip, 0.1f0)
GLWindow.render_frame(w)
channel=:depth
img = screenbuffer(w, channel) 

save("test.png",img)

```

The image should be looking directly in the center of the mug. 

[1_Coffeecup_final-03-Mar-2016-18-50-40.obj.txt](https://github.com/JuliaGL/GLVisualize.jl/files/262988/1_Coffeecup_final-03-Mar-2016-18-50-40.obj.txt)

**Comment by SimonDanisch** [comment]
Sorry I was traveling... This is a very annoying but easy to fix problem.
As you can see `eyeposition==up`, which is screwing things up, since they all must be orthogonal (they basically are the axis vectors for the camera space).
Try setting `up` to `Vec3f0(0,1,0)`.
Et voila:
![image](https://cloud.githubusercontent.com/assets/1010467/15511400/9bb75cb6-21db-11e6-882f-7306dff961f7.png)

**Comment by kleinash** [comment]
That did it. Thank you.
